-- ============================================================================
-- CORREÇÃO COMPLETA DA TABELA tunder_bot_logs
-- ============================================================================
-- 
-- PROBLEMAS IDENTIFICADOS:
-- 1. Coluna 'account_name' não existe (erro principal)
-- 2. Diferenças entre estrutura atual e documentação
-- 3. Falta de índices para performance
--
-- ERRO: Could not find the 'account_name' column of 'tunder_bot_logs' in the schema cache
--
-- SOLUÇÕES:
-- 1. Adicionar coluna 'account_name' para sistema multi-conta
-- 2. Padronizar tipos de dados conforme documentação
-- 3. Adicionar índices recomendados
-- ============================================================================

-- ESTRUTURA ATUAL (fornecida pelo usuário):
-- id bigint generated by default as identity not null,
-- operation_result text not null,
-- profit_percentage double precision not null,
-- stake_value double precision not null,
-- timestamp timestamp with time zone not null default now(),
-- created_at timestamp with time zone null default now(),
-- updated_at timestamp with time zone null default now(),
-- bot_name text null

-- ESTRUTURA ESPERADA PELO CÓDIGO:
-- Todas as colunas acima + account_name text

-- ============================================================================
-- CORREÇÕES NECESSÁRIAS
-- ============================================================================

-- 1. Adicionar a coluna account_name (PRINCIPAL)
ALTER TABLE public.tunder_bot_logs 
ADD COLUMN IF NOT EXISTS account_name TEXT NULL;

-- 2. Adicionar comentários para documentar as colunas
COMMENT ON COLUMN public.tunder_bot_logs.account_name IS 'Nome da conta Deriv utilizada para a operação (sistema multi-conta)';
COMMENT ON COLUMN public.tunder_bot_logs.bot_name IS 'Nome do bot que executou a operação';
COMMENT ON COLUMN public.tunder_bot_logs.operation_result IS 'Resultado da operação (WIN/LOSS)';
COMMENT ON COLUMN public.tunder_bot_logs.profit_percentage IS 'Percentual de lucro/prejuízo da operação';
COMMENT ON COLUMN public.tunder_bot_logs.stake_value IS 'Valor da aposta em USD';

-- 3. Criar índices para melhorar performance
CREATE INDEX IF NOT EXISTS idx_tunder_bot_logs_account_name 
ON public.tunder_bot_logs(account_name);

CREATE INDEX IF NOT EXISTS idx_tunder_bot_logs_bot_name 
ON public.tunder_bot_logs(bot_name);

CREATE INDEX IF NOT EXISTS idx_tunder_bot_logs_created_at 
ON public.tunder_bot_logs(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_tunder_bot_logs_result 
ON public.tunder_bot_logs(operation_result);

-- 4. Índices compostos para consultas complexas
CREATE INDEX IF NOT EXISTS idx_tunder_bot_logs_account_date 
ON public.tunder_bot_logs(account_name, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_tunder_bot_logs_bot_date 
ON public.tunder_bot_logs(bot_name, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_tunder_bot_logs_result_date 
ON public.tunder_bot_logs(operation_result, created_at DESC);

-- 5. Índice para análises multi-conta
CREATE INDEX IF NOT EXISTS idx_tunder_bot_logs_account_bot_date 
ON public.tunder_bot_logs(account_name, bot_name, created_at DESC);

-- ============================================================================
-- VERIFICAÇÃO DA ESTRUTURA ATUALIZADA
-- ============================================================================
-- Execute este comando para verificar se a coluna foi adicionada corretamente:
-- 
-- SELECT column_name, data_type, is_nullable 
-- FROM information_schema.columns 
-- WHERE table_name = 'tunder_bot_logs' 
-- AND table_schema = 'public'
-- ORDER BY ordinal_position;
--
-- ============================================================================
-- ESTRUTURA FINAL ESPERADA:
-- ============================================================================
-- 
-- Colunas da tabela tunder_bot_logs após a correção:
-- 1. id (bigint) - Chave primária
-- 2. operation_result (text) - Resultado da operação
-- 3. profit_percentage (double precision) - Percentual de lucro
-- 4. stake_value (double precision) - Valor da aposta
-- 5. timestamp (timestamp with time zone) - Timestamp da operação
-- 6. created_at (timestamp with time zone) - Data de criação
-- 7. updated_at (timestamp with time zone) - Data de atualização
-- 8. bot_name (text) - Nome do bot
-- 9. account_name (text) - Nome da conta Deriv [NOVA COLUNA]
--
-- ============================================================================

-- Opcional: Atualizar registros existentes com um valor padrão
-- UPDATE public.tunder_bot_logs 
-- SET account_name = 'Bot_Principal' 
-- WHERE account_name IS NULL;

-- ============================================================================
-- INSTRUÇÕES DE EXECUÇÃO:
-- ============================================================================
-- 
-- 1. Acesse o painel do Supabase
-- 2. Vá para SQL Editor
-- 3. Cole e execute este script
-- 4. Verifique se a coluna foi criada corretamente
-- 5. Teste o bot Python novamente
--
-- ============================================================================