# Netlify configuration file

# Handle Single Page Application routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirect for Supabase auth callbacks
[[redirects]]
  from = "/auth/callback"
  to = "/index.html"
  status = 200
  
# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()" 